version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=changeme-secret
      - OPENSEARCH_URL=http://opensearch:9200
    depends_on:
      - opensearch

volumes:
  opensearch-data:
