name: Deploy All Services

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy OpenSearch
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd /opt/opensearch-mvp && \
            git pull origin main && \
            docker-compose -f docker-compose.opensearch.yml down && \
            docker-compose -f docker-compose.opensearch.yml up -d && \
            echo "Waiting for OpenSearch to be ready..." && \
            sleep 30
          '

      - name: Deploy Web Application
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd /opt/opensearch-mvp && \
            docker-compose -f docker-compose.web.yml down && \
            docker-compose -f docker-compose.web.yml up -d --build && \
            docker-compose -f docker-compose.web.yml exec -T nextjs-app npx prisma migrate deploy
          ' 